

install:
	# pip install torch
	pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
	pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
	pip install -q torch-geometric
	pip install ogb

